In [1]:
from utils import extract_and_melt

import warnings
warnings.filterwarnings('ignore')

Check your chrome version searching for chrome://version. If your chrome version is 115 or newer, you can install chromedriver here https://googlechromelabs.github.io/chrome-for-testing/#stable. Else, check it here https://chromedriver.chromium.org/downloads. After downloading, unzip the file, move it to the same folder as this notebook and inform the path in the next cell.

----

# **ILCA 7:** WORLD CHAMPIONSHIP 2022

In [2]:
URL = 'https://2022ilca7men.ilca-worlds.org/wp-content/uploads/sites/2/2022/06/ILCA7Men-FINAL.html'

colunas = ['Posição Geral', 'Flotilha', 'Nome Competidor', 'MNA', 'Sail', 'ISAF ID', 
           'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 
           'Pontuação Total', 'Nett']

df = extract_and_melt(URL = URL,
                      CAMPEONATO = 'World Championship 2022',
                      ID_CAMPEONATO = 12,
                      CLASSE = 'Ilca 7', 
                      COLUNAS = colunas)

df.head()

,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição
0,Jean-Baptiste Bernaz,12,Ilca 7,(19),None,1,,134,51,World Championship 2022
1,Pavlos Kontides,12,Ilca 7,(11),None,2,,106,68,World Championship 2022
2,Filip Jurišic,12,Ilca 7,3,None,3,,140,75,World Championship 2022
3,Thomas Saunders,12,Ilca 7,4,None,4,,113,77,World Championship 2022
4,Tonci Stipanovic,12,Ilca 7,5,None,5,,144,81,World Championship 2022

----
# **ILCA 7:** EUROPEAN CHAMPIONSHIP 2023

In [3]:
URL = 'https://eurilca.eu/documents/273/results/ilca7g.htm' # gold fleet

colunas = ['Posição Geral', 'Flotilha', 'Nat', 'Sail Number', 'Nome Competidor', 'Trophy',
           'Q1', 'Q2', 'Q3', 'Q4', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'Pontuação Total', 'Nett']

df = extract_and_melt(URL = URL,
                      CAMPEONATO = 'European Championship 2023 - Gold Fleet',
                      ID_CAMPEONATO = 6,
                      CLASSE = 'Ilca 7',
                      COLUNAS=colunas)

df.head()

,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição
0,STIPANOVIC Tonci,6,Ilca 7,(7.0),None,1,,63.0,41.0,European Championship 2023 - Gold Fleet
1,JURISIC Filip,6,Ilca 7,(63.0 ufd),None,2,,129.0,42.0,European Championship 2023 - Gold Fleet
2,WEARN Matthew,6,Ilca 7,1.0,None,3,,73.0,48.0,European Championship 2023 - Gold Fleet
3,KONTIDES Pavlos,6,Ilca 7,(19.0),None,4,,102.0,62.0,European Championship 2023 - Gold Fleet
4,WILLIM Nik Aaron,6,Ilca 7,(24.0),None,5,,128.0,67.0,European Championship 2023 - Gold Fleet

In [4]:
URL = 'https://eurilca.eu/documents/273/results/ilca7s.htm' # silver fleet

colunas = ['Posição Geral', 'Flotilha', 'Nat', 'Sail Number', 'Nome Competidor', 'Trophy',
           'Q1', 'Q2', 'Q3', 'Q4', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'Pontuação Total', 'Nett']

df = extract_and_melt(URL = URL,
                      CAMPEONATO = 'European Championship 2023 - Silver Fleet',
                      ID_CAMPEONATO = 6,
                      CLASSE = 'Ilca 7',
                      COLUNAS=colunas)

df.head()

,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição
0,BOITE Alexandre,6,Ilca 7,26.0,None,1,,160.0,91.0,European Championship 2023 - Silver Fleet
1,HOFFMANN Julian,6,Ilca 7,28.0,None,2,,173.0,107.0,European Championship 2023 - Silver Fleet
2,UUSITALO Valtteri,6,Ilca 7,(27.0),None,3,,181.0,124.0,European Championship 2023 - Silver Fleet
3,RUITENBERG Luke,6,Ilca 7,(33.0),None,4,,215.0,133.0,European Championship 2023 - Silver Fleet
4,PAPADIMITRIOU Dimitris,6,Ilca 7,39.0,None,5,,230.0,136.0,European Championship 2023 - Silver Fleet

In [5]:
URL = 'https://eurilca.eu/documents/273/results/ilca7b.htm' # bronze fleet

colunas = ['Posição Geral', 'Flotilha', 'Nat', 'Sail Number', 'Nome Competidor', 'Trophy',
           'Q1', 'Q2', 'Q3', 'Q4', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'Pontuação Total', 'Nett']

df = extract_and_melt(URL = URL,
                      CAMPEONATO = 'European Championship 2023 - Bronze Fleet',
                      ID_CAMPEONATO = 6,
                      CLASSE = 'Ilca 7',
                      COLUNAS=colunas)

df.head()

,Nome Competidor,ID Competição,Classe Vela,Pontuação Regata,Flotilha,Posição Geral,Punição,Pontuação Total,Nett,Nome Competição
0,ELLIOTT-SHIRCORE Stefan,6,Ilca 7,(52.0),None,1,,185.0,84.0,European Championship 2023 - Bronze Fleet
1,MOUTOUT Jeremy,6,Ilca 7,28.0,None,2,,240.0,123.0,European Championship 2023 - Bronze Fleet
2,KRABBE-CHRISTENSEN Andreas,6,Ilca 7,(63.0 ufd),None,3,,235.0,125.0,European Championship 2023 - Bronze Fleet
3,FLOWER Ben,6,Ilca 7,(51.0),None,4,,249.0,135.0,European Championship 2023 - Bronze Fleet
4,BRUCE Liam,6,Ilca 7,36.0,None,5,,232.0,143.0,European Championship 2023 - Bronze Fleet